### ISSUE TITLE
Fertiliser Treatments

### ISSUE THREAD

**Issue by Afiasarwar** [APSIMInitiative/APSIMClassic#1787]
hello every one.I am applying different fertiliser treatments in APSIM that is Urea _N 50 kg/ha at sowing and 50kg/ha 2 months after sowing to check its effect on yield  but it does not effect yield.I checked summary file and fertiliser is added there but still no effect on yield.can anyone guide me in this regard?
Thanks

**Comment by peter-devoil** [comment]
Hi afia,
A few months ago on the old bulletin board, somebody encountered a similar problem; it turned out that a) there was a lot of N already in their system and b) they were modelling (very long duration) winter wheat and were in fact doubling up on fertiliser as their crop was growing so long... 

I suggest you try reducing the amount of N (via starting N & OC%) until you see an effect.

You can use the tracker module to tell you how much fertiliser is applied from sowing to harvest.

**Comment by Afiasarwar** [comment]
Thank you peter...Its been 4 months that i am facing this issue but now finally it has been solved.I just changed Initial N and OC and now different fertiliser amount actually effect the yield.Thank you once again.

**Comment by Afiasarwar** [comment]
Thank You Peter...for so long i was really stuck but now my issue has been
solved just by changing initial nitrogen and Oc %.Thank you once again.

**Comment by BenAbabaei** [comment]
@Afiasarwar you can close this issue if your question has been answered. Cheers.
