### ISSUE TITLE
New releases are not being branded correctly

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/APSIMClassic#1853]
New installers are being generated with the correct file name but incorrect version info.

**Comment by hol430** [comment]
This is still broken.

**Comment by peter-devoil** [comment]
Hey @hol430, it appears that when building an apsim away from jenkins, the version stamper tries to use the git hash as a revision number. That's mostly harmless, but the .NET components have started objecting to it (it's not a number). I'm wondering if we keep the hash for all the C runtimes (ie so it shows up in summary & outputfiles), but use 0 or similar for the .NET assemblies.

**Comment by hol430** [comment]
Makes sense. It is handy seeing the git hash in the summary/output files so you know (roughly) what your source code looked like when you ran the file. As it works currently, it will fail if git is not on path though, so maybe it should fallback to using 0 if it can't find git.

**Comment by tsauvajon** [comment]
I think this is related, I'm getting the following error when building the latest commit (on Linux):
```
The specified version string `7.10..0' does not conform to the recommended format major.minor.build.revision. Line number: 2
      at DLLProber.CompileProxyDLL () [0x001dd] in <457670be1d0c450db74d3602db3b5d92>:0
      at Types.RefreshProbeInfoForAll () [0x00089] in <457670be1d0c450db74d3602db3b5d92>:0
      at Program.Main (System.String[] args) [0x0000e] in <338660cde91c42bf8ebdf6f58ee0c8c7>:0
```

It looks like it's missing the build number. 
By looking at the code, having an empty RevisionNumber [here](https://github.com/hol430/APSIMClassic/blob/da44aa4199430c7c0ec8058ff2368b463e39458e/Model/Build/VersionStamper.cs#L26) is likely to cause that issue.


I'm building APSIM on Linux by downloading the source as zip (not `git cloning`) because it is way faster, so I don't have any `git` info such as git commit (although I could easily have it available through an environment variable).

It appears to me that setting `Macros["RevisionNumber"]` to anything would allow this step to succeed. How can I set this value?

**Comment by peter-devoil** [comment]
Glad you found the workaround - we'll have a look at this case. We are big on having some sort of unique identifier embedded in the model outputs - it makes comparisons with other people's work much simpler - and a link back to some point in version control is essential.

**Comment by hol430** [comment]
Reopening as there seems to be a problem here with the C#/VB components, my recent change wasn't very well thought through.
