### ISSUE TITLE
Evapotranspiration and PET Confusion

### ISSUE THREAD

**Issue by adam-weis** [APSIMInitiative/APSIMClassic#1877]
I'm having some trouble understanding how APSIM calculates actual and potential evapotranspiration, ET and PET. The documentation that exists seems spread out, so I'm relying on SWIM manuals (not sure if this is right or not). Note that I've been using SWIM instead of SoilWat for the water balance modules.

In the SWIMv2.1 manual page 30 (https://www.apsim.info/wp-content/uploads/2019/09/SWIMv21UserManual-1.pdf) it says soil evaporation is calculated using the Campbell 1985 isothermal vapor transport formulation, and transpiration (plant water uptake) is calculated using crop-specific parameters in a resistance network similar to Ohm's Law. Then soil evap + transp = actual ET. However, it says PET is an input to the model.

In the SWIM3 documentation, which is used in APSIM (https://www.apsim.info/documentation/model-documentation/soil-modules-documentation/swim3/) it says PET is calculated using Priestly-Taylor, and I assume soil evap and plant water uptake are calculated in the same way as SWIMv2.1?

Does APSIM use PET (reported as output variable 'eo') for anything? For instance, to calculate actual ET (much like how many people use crop coefficient, KC)?

Am I understanding the calculations right:
- Soil evaporation uses Campbell 1985 and is reported as variable 'eos' then modified for green and residue cover and reported as actual soil evap 'es'
- Plant water uptake/transpiration uses the resistance network method, relying on crop-specific parameters for water demand, and reported as variable 'ep'
- Actual ET isn't directly reported, but can be calculated by adding: es + ep = ET?
- PET uses Priestly-Taylor and is reported as variable 'eo' but then isn't used to calculate any actual ET?

Please let me know if I'm understanding things right or not, or if anyone knows of better documentation out there.

Thank you!

**Comment by peter-devoil** [comment]
@hut104 or @sno036 might know the details here.

**Comment by sno036** [comment]
It is way too complicated in Classic and depends on what models you have in the simulation. If you add Micromet (might be called MicroClimate?) then it uses Penman-Monteith for potential ET and then this is aggregated to potentials for the crops and soil water evaporation in the usual ways. Actual ET is got from the individual crops and soil water balance and each uses their own methods. Note that not all crops are compatible with Micromet. I don't use APSIM without Micromet so am unsure what happens when it is not in the simulation other than I understand that it is a Priestley-Taylor method.

For your second question, that applies to standalone SWIM (for which the manual was written) or an implementation called "SWIM2ui" which is horrendous to use but not for SWIM3 in which the crops do their own uptake methods using KL.

Third question - yes.

Fourth question answered above.

**Comment by hut104** [comment]
Agree with Val.
APSIM is not like many models which calculate some potential for the system and disaggregate this.  Individual models calculate rates.
We probably need some sort of document that explains this.

**Comment by sno036** [comment]
> We probably need some sort of document that explains this.
Or retire Classic ....

**Comment by peter-devoil** [comment]
Do we have a volunteer for writing documents and/or retiring classic?

**Comment by sno036** [comment]
@adam-weis - you are probably not finding this highly illuminating of your original question!

TBH - I have about zero enthusiasm for spending my time documenting APSIM Classic. Getting something more solid on PET in NextGen is a different matter and worth some effort.

**Comment by adam-weis** [comment]
@sno036 no this has been helpful and I appreciate you all responding!

**Comment by peter-devoil** [comment]
No worries, @adam-weis - you can close the issue if you feel it has been answered. Whatever you do, keep pestering us to document our models properly!
