### ISSUE TITLE
About the "summaryfile" component reporting an error

### ISSUE THREAD

**Issue by guochaoqiong** [APSIMInitiative/APSIMClassic#1893]
The model runs successfully, but the "summaryfile" component has a yellow exclamation point "Goto next warning". Does this mean that the model is wrong? The results of the simulation are not available?

**Comment by peter-devoil** [comment]
Any warnings or errors in the summary file should be inspected. They're a clue to a potential inconsistancy that may invalidate your results. Outputs may be generated, but may include errors.

**Comment by guochaoqiong** [comment]
@peter-devoil 
thanks!
I did the rice-wheat rotation exercise in South Asia and found that there was a warning whether it was the model I rebuilt or the model provided by the official website. So there's nothing wrong with this model?

**Comment by peter-devoil** [comment]
It depends on the message. I know there are a few warnings with old manager 1 scripts about "possible use of uninitialised variable" that can be safely ignored, but, to be sure you have to check each one. 

For safety, it's better to fix the code that is giving the warning, so that when apsim gives you a genuine warning you are aware of it - not ignoring it..
P

**Comment by guochaoqiong** [comment]
@peter-devoil 
ok, thanks a lot
