### ISSUE TITLE
SWIM3 failed to find solution

### ISSUE THREAD

**Issue by germanmandrini** [APSIMInitiative/APSIMClassic#1901]
I am using SWIM to run multiple simulations and I get frequent errors. When I use SoilWatthat doesn't happen. What could be the cause?
Attached is a simulation that failed. Are there some consideration I should have when building the soil files for APSIM that are different than for SoilWat?
Thanks
[swim_failed.zip](https://github.com/APSIMInitiative/APSIMClassic/files/4976351/swim_failed.zip)

**Comment by peter-devoil** [comment]
This is an inherent "feature" of the way the model finds a solution each day - when it hits boundary conditions (eg a flood), the model's internal PDE solver often gets lost. @hut104 or @sno036 might have more detail, but in short - this is why people don't like using [richards' equation](https://en.wikipedia.org/wiki/Richards_equation) with raw data.

**Comment by sno036** [comment]
Actually SWIM is pretty stable. I was not able to run the simulation - too many XML files not included. Try decreasing the maximum time step and/or the maximum water increment in SWIM.

**Comment by germanmandrini** [comment]
Thanks for your answers. I tried decreasing the maximum time step and the maximum water increment but still get the error. Sorry I forgot to include the other xml files. Attached is a new one that has everything so you can run it and get the error.
[swim_failed2.zip](https://github.com/APSIMInitiative/APSIMClassic/files/4982630/swim_failed2.zip)

**Comment by hut104** [comment]
If I believe the summary file, the discretisation of space is all mixed up
     ---------------------------------------------------------------
      x    dlayer   BD   SW     LL15   DUL   SAT      Ks      Psi
     ---------------------------------------------------------------
        0.0   50.0  1.30  0.340  0.220  0.340  0.460  47.28   -100.0
      100.0   50.0  1.30  0.340  0.220  0.340  0.460  47.28   -100.0
      100.0   50.0  1.30  0.340  0.220  0.340  0.460  47.28   -100.0
      200.0   50.0  1.30  0.340  0.220  0.340  0.460  47.28   -100.0
      200.0  200.0  1.31  0.340  0.210  0.340  0.460  47.12   -100.0
      600.0  200.0  1.32  0.330  0.200  0.330  0.450  45.45   -100.0
      600.0  200.0  1.34  0.320  0.180  0.320  0.450  46.62   -100.0
     1000.0  200.0  1.38  0.300  0.160  0.300  0.420  67.41   -100.0
     1000.0  500.0  1.49  0.250  0.140  0.250  0.400 161.08   -100.0
     2000.0  500.0  1.55  0.220  0.130  0.220  0.390 219.03   -100.0
     ---------------------------------------------------------------


I’d suggest you try using a different layer structure, with thin layers at the surface as per the swim examples.

**Comment by germanmandrini** [comment]
Thanks @hut104. I am running APSIM in a grid and I changed the layer structure of the soils to the SWIM example located in the standard toolbox. I think is working slightly better, but still many simulations fail. Attached is an example. Would you check if anything is wrong there? 
[1128_162721_14_stab.zip](https://github.com/APSIMInitiative/APSIMClassic/files/5017547/1128_162721_14_stab.zip)

**Comment by sarchontoulis** [comment]
German, i think the problem comes from your bottom boundary condition (currently set as no water gets in/out from the bottom). Once you remove this, the sim will go through with no errors. In your example, SWIM failed because your entire soil profile was saturated with water, and we are talking about a very sandy soil (dul = 0.05).

**Comment by germanmandrini** [comment]
Thank you Sotirios. I cannot find any documentation that explains how bbc_gradient and bbc_potential work, and how that relates to the depth of the water table (the one we can set in SWIM, not in the manager-script). Is there any place where I can learn about it?
In a paper, I found that bbc_potential=0 means that the WT is at the bottom of the specified profile. That means we don't get N leaching through the tiles, but the soil will get water from the water table when the roots get close to it? If I want to measure the tiles effect on N-leaching I need to not set the bbc_potential but then we get those errors if the entire soil profile gets saturated?

**Comment by sarchontoulis** [comment]
German

Here two documents:
https://www.apsim.info/wp-content/uploads/2019/09/SWIMv21UserManual.pdf
https://www.apsim.info/documentation/model-documentation/soil-modules-documentation/swim3/

In brief:
bbc_potential = e.g. 100 cm or 150 cm will fluctuate the water table around that depth. This is the default in 7.10 when you bring in swim.
bbc_gradient = -1 seals the bottom of the profile (no drainage)
bbc_gradient = 1 is a free drainage condition similar to soilwat

SWIM offers lots of flexibility but you have to know what drives the watertable in your field to inform the model. In my experience, most failures comes with the -1 because there are situations with too much water.

**Comment by germanmandrini** [comment]
That solved it. Thanks!
