### ISSUE TITLE
Minor versions of 7.10 give different maize yield results

### ISSUE THREAD

**Issue by mnowatzke** [APSIMInitiative/APSIMClassic#1905]
Minor versions (I tried three- r4158, r4200, r4207) of 7.10 give significantly different maize yield results (10500 for r4158 vs 9500) for the exact same file. Wondering what changed between the older and newer versions and how I can address it.

**Comment by jbrider** [comment]
@mnowatzke The model has been under continuous improvement since r4158 - particularly in the last 12 months.
All of the changes have caused improvements to the accuracy of the model with respect to the validation datasets that we have used.  I'm not sure what you mean by how you address it? Did your simulation contain cultivars that were calibrated using v4158 and now gives worse results?

**Comment by mnowatzke** [comment]
@jbrider Thank you. Yes, the custom cultivars I am using were calibrated with a much earlier version. Do you know if there is any documentation identifying what changes to the model were made? Thanks again.
