### ISSUE TITLE
Urgent training course Q: Sporadic problem with reading of output file in XY graphs of GUI

### ISSUE THREAD

**Issue by uqschap7** [APSIMInitiative/APSIMClassic#1933]
I've been running some online basic training in APSIM for plant breeding students in Spain this week. Several students, all running French version of Windows 10 have had a problem reading the output files to display graphs. For most of them, it seems to have worked at least once, but now at least 3 students have had problems where
1. The output file looks fine - is for Exercise 1 of the Training manual for APSIM classic
2. When they go to select the columns in the XY graph, most of the columns are blank.

Looks like some issue with reading the output files into the XY GUI - maybe related to automated parsing of the output file in different versions of Windows?

Some screen shots are attached.

Would be good to get an answer today if possible so I can let students know tonight.

thank you,
scott

[Module1.zip](https://github.com/APSIMInitiative/APSIMClassic/files/5351327/Module1.zip)

![Capture d’écran (226)](https://user-images.githubusercontent.com/69138164/95514496-61612900-09ff-11eb-8fe1-4ecb8ab3ae81.jpg)
![Capture d’écran (227)](https://user-images.githubusercontent.com/69138164/95514506-658d4680-09ff-11eb-92df-78f92767c955.jpg)
![Capture d’écran (228)](https://user-images.githubusercontent.com/69138164/95514517-67efa080-09ff-11eb-9047-c11a7188c5dc.jpg)
![Capture d’écran (229)](https://user-images.githubusercontent.com/69138164/95514522-6a51fa80-09ff-11eb-868c-1d12ba75f8f9.jpg)

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel

**Comment by Keith-Pembleton** [comment]
Hi Scott
I have just tried your simulation in an English version of windows and it works fine.  
What happens if you use the next node down (named "G") and the browse button to manually point APSIM to the Clay fallow output file?  

Also (as a wild guess) try getting the students to delete all the old .out files out of their working directory and shorten the path to the working directory.  One of my students in the past had a particular version of windows set up that did not like long paths and lots of .out files for some reason.  

A work around for the students (albeit far from ideal) would be to bring the .out file into something like excel and then create the figures there.     

Cheers
Keith

**Comment by uqschap7** [comment]
Thanks Keith - yes, only 3 out of about 40 students had this problem, and I had no problems with running it on a virtual machine with Windows in Spanish. 

We did try to browse the file again, but didnt work.
I will suggest that they change the path.
ta

**Comment by Keith-Pembleton** [comment]
its only a wild guess, but fingers crossed

**Comment by MarkLieffering** [comment]
Another wild guess - seeing as it only the French Windows that seem to be causing problems (?) - something to do with the regional and/or language settings regarding the comma/decimal system used?

**Comment by peter-devoil** [comment]
Seconded for a regionalisation issue - we've seen it so many times that on the download page, it now states "...International users running Microsoft Windows may have trouble with number & date formatting (eg commas vs decimal points in numeric entries), and may need to change their regional settings to Australian or similar."

**Comment by EnliWang** [comment]
Further to Peter's comment - not sure it is related to the issue raised by Scott:

Our Chinese students/colleagues needed to change the dates into Australian format as well.

**Comment by uqschap7** [comment]
ok. I didn't want to blame Windows per se if this is a problem we have seen before? We always have issues with US formats, but less so with Europe. Does anyone know if the APSIM GUI automatically uses the Windows/Excel settings for column separators when writing or reading? APSIM creates space delimited columns, but I guess that perhaps the filereader is getting some info from Windows in order to separate the columns and present to the users. Can we verify this?

**Comment by Keith-Pembleton** [comment]
Looking at the screen shots it is more likely something to do with a comma as a decimal rather than a column separator.  The date, day and year columns are being displayed fine.  I immediately did not think regional settings because the dates are being displayed correctly.  Is APSIM in this case picking up the regional settings, and then expecting a comma as the decimal in the .out file but only finding stops?

**Comment by peter-devoil** [comment]
Yes, the gui does use windows settings, but the model doesn't. So - if its running under french regional settings, the gui will try and interpret numbers (eg from met files) as "30,5" and when the model runs, it will expect "30.5". 

Its a real mess that comes from having parts that use a runtime (c++/fortran) built well before internationalisation. Safest approach is to become an australian for the day.
