### ISSUE TITLE
Simulations showing the relationship between growing degree days, photoperiod and crop phenology

### ISSUE THREAD

**Issue by Lionckelet** [APSIMInitiative/APSIMClassic#1974]
Good afternoon everybody,

I would like to know if it is possible on APSIM to obtain graphs that illustrate the number of Growing Degree Days required for a crop to pass from one phenological stage to the next. I would also like to be able to do this with the photoperiod. If this is feasible, could you explain to me how to proceed, please? 

Although I find the software quite clear, I'm just starting out and I haven't found out how to do it in trainings. I saw that it was possible to use the variables "zadok_stage" and "TT" which can surely be useful for this goal, but I'm not sure how to do it.

Thank you very much,
Have a good day

**Comment by peter-devoil** [comment]
Hi,

One of the "missing training modules that hasnt been written yet" is the topic of plant growth - and as all of our hosting institutions are highly plant oriented, it's a perversity that it's missing, yet the reason it is missing is rooted in the complexity of the subject. I encourage you to ask for help whenever the opportunity presents, if enough people clamour for the materials, somebody will do something about it..

There are several ways to do what you want; firstly: apsim uses the concept of physiological stages where each stage represents an phase in the lifecycle (eg grainfilling), wheras the zadok scale is developmental - there isn't a 1:1 match between the two. So choose your "division" wisely.

Secondly, not every phase is sensitive to photoperiod, so "make sure you know the answer before doing the experiment" - that the plant you're exploring has the properties you're interested in. Note that many plant functions in apsim have a flat response not because it's real, but because the module authors don't have the data to justify anything else.

Finally, you'll find a bunch of variables (in wheat) called TTAfterXYZ - each the amount of TT the plant spent after beginning phase XYZ. Write these out at harvest and in the analysis package of your choice (eg R, excel etc) calculate the running difference of each sequential phase. Run this simulation over several sowing dates and you'll see the PP effect showing in some columns but not others.

**Comment by Lionckelet** [comment]
Hello Peter,

Thank you for your quick answer, is it really helpfull. I will try to dig this.
