### ISSUE TITLE
Soil Evaporation U and Cona

### ISSUE THREAD

**Issue by MHMDHMIMOU** [APSIMInitiative/APSIMClassic#1983]
Hello APSIM community,

Happy to join APSIM users community recently!

While I am configuring APSIM files for simulation running, I found in the Soil file (***.soils**) (in soil water section) the parameters U and Cona (for summer and winter).

I am wondering:
- what those parameters mean (I found some resources in APSIM website but they were not enough to get clear understanding)?
- how to estimate them for a given soil?
- what soil laboratory analysis parameters are they used in estimating U and Cona? 
- Are there any formulas to compute U and Cona from soil parameters?

I appreciate your kind support!

Regards,
Mohammed
Mohammed VI Polytechnic University
https://www.um6p.ma/en

**Comment by peter-devoil** [comment]
Cona & U represents a two stage drying curve - full details from your library: Ritchie, J. T. (1972). A model for predicting evaporation from a row crop with incomplete cover. Water Resources Research 8, 1204-13. Most people use published values, unless they've got a lysimeter to say otherwise.

There are some links at the end of https://github.com/APSIMInitiative/APSIMClassic/issues/1886 that will also cover parts of this.
