### ISSUE TITLE
Looking for the equations code file

### ISSUE THREAD

**Issue by abbouhenache** [APSIMInitiative/APSIMClassic#1990]
Hi everyone,

I'm looking for the different process equations in APSIM (e.g. equations of P) to do a fully documentation work, is there an engine file code?
Can you please tell me where to find that?

Thanks

**Comment by peter-devoil** [comment]
The [soil P](https://www.apsim.info/documentation/model-documentation/soil-modules-documentation/soilp/) science document describes a general overview, and the referenced papers should have the "equations".

Unfortunately, [the code](https://github.com/APSIMInitiative/APSIMClassic/blob/master/Model/SoilP/SoilP.f90) is obfuscated by software terminology and not easily understood. Be careful - just because you find an equation implemented there doesnt mean it's being used.

**Comment by abbouhenache** [comment]
@peter-devoil okay, i see! thank you so much for the answer and the remark
