### ISSUE TITLE
How to calculate the genetic parameters of rice in the APSIMClassic 7.1?

### ISSUE THREAD

**Issue by mrsunhuang** [APSIMInitiative/APSIMClassic#2014]
Dear users
Excuse me，How to calculate the genetic parameters of rice in the APSIMClassic 7.1?

**Comment by sarahcleary** [comment]
@andomariot; @Chloe0317; @DonaldGaydon - can one of you assist?  thanks.

**Comment by andomariot** [comment]
Hi,
The genotypic parameters for developmental rate (DVR) for rice variety in APSIM can be estimated using observed panicle initiation date, flowering time and physiological maturity. The values of the different DVRs  to input are the inverse of the accumulated degree days  required to reach the given stage. For example DVRJ- is the inverse of accumulated degree days from sowing to complete the basic vegetative stage. You may refer to the manual of calibration of the ORYZA model (https://sites.google.com/a/irri.org/oryza2000/calibration-and-validation/model-calibration) for more details as rice model in APSIM classic use same plant representation as in  ORYZA model.

**Comment by DonaldGaydon** [comment]
The primary genetic parameters you need to modify for calibrating/parameterising your rice variety are the phenology-related ones (DVRI, DVRJ, DVRP, DVRR. MOPP, PPSE).  We normally start with simulating your experiment using a default variety in the oryza.xml file, then compare the simualted phenolgy with the observed.  Then incrementally modify the previously-mentioned parameters until simualted phenology matches observed.  This is detailed in Gaydon et al., 2017
[APSIM in Asia - Gaydon et al 2017 FCR.pdf](https://github.com/APSIMInitiative/APSIMClassic/files/6152785/APSIM.in.Asia.-.Gaydon.et.al.2017.FCR.pdf)

Since the APSIM rice model (APSIM-Oryza) uses the code of the ORYZA2000 module, the documentation on determining/ calibrating the genetic varietal parameters provided by IRRI is also applicable.  I suggest you also examine the following webpage and associated links [https://sites.google.com/a/irri.org/oryza2000/home ](url) 

Good luck
