### ISSUE TITLE
cotton calibration

### ISSUE THREAD

**Issue by xuyang7912** [APSIMInitiative/APSIMClassic#2031]
Exception has been thrown by the target of an invocation!  I would like to ask about the reasons and solutions for the error reported in adding the ini cotton parameter

**Comment by xuyang7912** [comment]
![Uploading QQ图片20210407111316.jpg…]()

**Comment by xuyang7912** [comment]
![error](https://user-images.githubusercontent.com/81681934/113800776-21021e00-978a-11eb-9331-a6b68677a02f.jpg)

**Comment by BrianCollinss** [comment]
@xuyang7912 Hi. Can you run any othe rsimulation in APSIM? I am asking this to make sure your langugage (locale) setting is not the cause.

**Comment by xuyang7912** [comment]
@BrianCollinss Thank you for your reply, I can simulate normally without adding the ini file, but after adding the ini file there is an exception. I have tried to simulate other crops, such as Continuous wheat and Continuous potatoes, and after adding the ini file it still simulates normally without any exceptions

**Comment by BrianCollinss** [comment]
Could you please let us know what the non-English message above "Component name: paddock" say?

**Comment by xuyang7912** [comment]
@BrianCollinss Exception has been thrown by the target of an invocation!

**Comment by peter-devoil** [comment]
That message is very common, and unfortunately tells all of us nothing. 

To solve your problem, I would take the system .ini file from the installation directory, and see if the simulation can run with that - if it can't then there are big problems.

Then add your changes bit by bit to see which part of the model is breaking.

**Comment by byzheng** [comment]
Possible to check whether your ini file in the folder with non-english characters or spaces. 

Better to have a screen for the whole tree or an example file.

**Comment by xuyang7912** [comment]
@byzheng Thank you for your reply,E:\Download\APSIM710-r4217\Model，This is the path to the file,the ini files for all crops are in this folder, but it doesn't work properly when simulating cotton.

**Comment by xuyang7912** [comment]
@peter-devoil Thank you for your reply. After removing the system.ini file from the installation directory, the simulation does not work properly, I am sure I have not adjusted the ini file for cotton, I do not know why other crops can be simulated properly while cotton cannot

**Comment by DavidJohnston491** [comment]
@xuyang7912 Cotton is a non-standard APSIM component. You cannot use ini files with it. Modifications to settings are done through the 'Advanced' button on the Cotton component window within the APSIM GUI.
Let me know what settings you are trying to adjust and I will try to assist.

**Comment by xuyang7912** [comment]
@DavidJohnston491 Thank you for your reply.Is that what you are referring to?How do I figure out what each variable means?
![image](https://user-images.githubusercontent.com/81681934/113998369-9570b600-988b-11eb-8201-8b319b275710.png)

**Comment by DavidJohnston491** [comment]
@xuyang7912 Yes, these are the input variable settings.  You could refer to Brian Hearn's original OZCOT paper (Hearn, AB 1994, 'OZCOT: A Simulation Model for Cotton Crop Management', Agricultural Systems, vol. 44, pp. 257-99.) as the model still follows this quite closely. Apart from this, to the best of my knowledge, no details have been publicly documented. The model was/is the IP of CSIRO Australia. That is why I offered to assist where I could, if you let me know what settings you are looking for.

**Comment by xuyang7912** [comment]
@DavidJohnston491 I want to simulate the yield of cotton in a semi-arid area, but I don't know which variables to adjust. I found that the crop parameters adjusted in the literature correspond to the parameters in the cotton.xml file, which also used the APSIM-OZCOT model.

**Comment by DavidJohnston491** [comment]
Okay, a fairly broad description. As with any crop calibration exercise, there will be many iterations to achieve sensible outcomes. Hopefully you have some trial crops in the same soil and similar environment that you are able to use for validation of simulation settings. 
The first thing with all APSIM simulations is to ensure you have your soil definition correct. This will determine much of the crop growth, especially the crop water interactions. Secondly, the crop root growth needs to be correct. Unfortunately this is primarily determined by observing the simulated crop growth. Too much growth and the roots are accessing too much water. Too little growth or unexpected death due to water stress and the roots are not accessing sufficient water. In the cotton model the root variables are: RFV_max (Root Front Velocity), specific_root_length (density of roots grown) and rootLACrit (Leaf Area needed before roots start to grow quickly - seedling setting). Of these the RFV_max is probably most significant and variable depending on the soil.
Many of the input variables in the list are not meant as user adjustable input settings, hence the lack of documentation. Most of these have been tuned for _Gossypium hirsutum L_  and do not need adjusting. A couple that might be worth noting are open_def (percent of open bolls that triggers transition to Maturity status and readiness for defoliation), and rtdep_max (maximum depth that roots can grow to - links with soil settings). Beyond this the 'cultivar' settings are generally of more interest. You can define a new cultivar by right clicking on the 'cultivars' node. Cultivars defined in the list are Australian commercial cultivars which are defined relative to some long standing, well proven cultivars. Unfortunately, without a common base from which to compare, defining new cultivars of unknown performance is a 'non-precise' art at best. That said, yield is a function of boll number X boll size X lint yield , the last two of which are defined in the cultivar settings. Of the cultivar settings, the most useful to adjust are the percent_l (gin turnout, percent of boll's weight returned as cotton lint), scboll (weight (size) of bolls in grams), and BckGndRetn (proportion of bolls retained by cotton plant under ideal conditions (opposite of default shedding)). Just remember to 'sow' your new cultivar from the sow command in the manager script.
Generally the approach is to ensure early LAI matches observed values up to 1st square. LAI and boll numbers match observed until first open boll. As fruiting continues watching for excessive LAI or sudden drops in LAI. Most errors in these areas relate to soil or root issues and the supply of water to the growing plant (ie not plant parameter adjustments). Delayed maturity and excess crop duration can relate to open_def not being reached, which might need the 60% reduced to 50% or 45% to stop the crop. Excessive early boll numbers and early crop termination can be triggered by BckGndRetn being set too high.  
As I said, many iterations to determine what is working and what is not. Best advice is always start with the soil and soil water. If it is wrong, not amount of calibrating the crop is going to work.
I wish you all the best with your research.

**Comment by xuyang7912** [comment]
@DavidJohnston491 After entering meteorological data and soil data, the crop parameter values are selected as default values and the yield is very low, only 300kg/ha, is this because the crop parameters are not adjusted?

**Comment by DavidJohnston491** [comment]
I will take this off line. Contact me directly on my email , myusername at gmail.com  .  Thanks.

**Comment by DavidJohnston491** [comment]
@xuyang7912  My apology if I was not clear in my previous comment. You can email me  ( DavidJohnston491 'at' gmail.com ) for more assistance.
A brief response to your previous question... There is no way of telling from the information that you have given as to whether the low yield is a reasonable outcome or not. Adjusting crop parameters is only going to give you minor adjustments. If the simulation is distinctly wrong, then the crop is not growing as it should, and this is most likely a problem with soil definitions or soil / crop water interactions. There are a number of reportable variables that will allow you to track where the problem lies. This is probably best done apart from this general forum.
