### ISSUE TITLE
n_stress_expand and swdef_expand ranges and meanings in wheat

### ISSUE THREAD

**Issue by JJguri** [APSIMInitiative/APSIMClassic#2082]
Could some one explain which is the difference between x_stress_expand and xdef_expand? I am using swdef_expand to test water stress on wheat simulations. However when I want to use the same parameter for N it does not exist. Therefore, I am using n_stress_expand. Although, they have the same value range 0-1, I can deduce that stress is higher close to 1 in n_stress_expand, which is the contrary for swdef_expand. While I can see values of n_stress_expand during a wet year, it is 0 during dry years. Is it because there was not a N stress on the crop under the dry year?

![image](https://user-images.githubusercontent.com/41041705/128801235-713f2f21-fbdb-4a07-ad09-820219e6f494.png)

**Comment by peter-devoil** [comment]
Each of those stick functions has a x_ABC and y_ABC parameter.
The x_ABC parameters are the x coordinates of the stick function, y_ABC similarly for y coords
Sometimes ABC relates supply:demand ratio to some stress process (eg leaf expansion here). 
You may not see N stress if there's no water flow to transport N?

**Comment by JJguri** [comment]
Thanks @peter-devoil . Could you please let me know where they are defined? Particularly swdef_expan and  n_stress_expand. I can see in one the stress is close to 1 and in the other close to 0, so I want to understand the ratio and the numerator and denominator of the ratios.

**Comment by peter-devoil** [comment]
It's [implemented here](https://github.com/APSIMInitiative/APSIMClassic/blob/cfeceaf62b2ca0435e7a9df9b93b68eee702ffcd/Model/Plant/PlantStress.cpp#L593). Parameters [read here](https://github.com/APSIMInitiative/APSIMClassic/blob/cfeceaf62b2ca0435e7a9df9b93b68eee702ffcd/Model/Plant/PlantStress.cpp#L562). Wheat [parameters here](https://github.com/APSIMInitiative/APSIMClassic/blob/cfeceaf62b2ca0435e7a9df9b93b68eee702ffcd/Model/Wheat.xml#L406).

If you want to explore it; do a 100 year (dryland) run with daily outputs of water supply (esw) & demand (Eo). Plot their ratio against swdef_expan, and verify it's the same slope as the parameters describe.

You'll find N calcs in the same file; but remember that N uptake only happens when water is being sucked out - ie by mass flow. If there's no water flow the calculation is irrelevant.

**Comment by JJguri** [comment]
thanks @peter-devoil, is there a variable/parameter which specified if there is enough mass flow or not for N uptake?. Otherwise, I need to classify seasons when the crop was under (or not) water stress and assume that when it was, the N uptake was not happening. I will explore the calculations of the N factors, so it they are 0 probably it is because there was not flow that day.

**Comment by JJguri** [comment]
@peter-devoil do you think the calculation of the NNI could be useful to assess the level of N stress during the growing season? I output this daily and as an average of the growing season. It was calculated as follows (Cte is only for comparison purposes):
```
if (biomass_wt > 0) then
	Na = biomass_n/biomass_wt*100
	NNI = Na/n_conc_crit
	Cte = 1
endif
```

**Comment by peter-devoil** [comment]
I'd leave that Q to somebody more qualified. There has been much discussion on the merits of using a target n concentration vs SLN. If I understand correctly, n_conc targets vary through the plant's lifecycle, where SLN doesn't. @uqghamme and @hut104 may have more detail, and certainly more reading material.
