### ISSUE TITLE
APSIM Maize and temperature stress

### ISSUE THREAD

**Issue by LenLon** [APSIMInitiative/APSIMClassic#2187]
Hello everyone, sorry to bother the github Issues page with these questions, but I can't find any documentation on some of the variables available for output from the maize module, namely:

`GrainTempFactor`
`temp_stress`

The Module documentation only refers to temperature stress as...

`There are no generic temperature factors, as for water and nitrogen stress, but as discussed in sections above temperature does influence grain N content, rate of senescence and radiation use efficiency (rue).`

I have found some reference to grain number being affected by temperature in the maize.xml ini file:

`GRAIN - Effect of temperature stress on Grain number
      -->
    <GrainTempWindow>-50 100</GrainTempWindow>
    <GrainHiTemperature type="text" description="Grain High Temperature">32 33 36 38</GrainHiTemperature>
    <GrainStressSeverity type="text" description="Severity of seed set stress">0 0.14 0.23 0.65</GrainStressSeverity>
`

So what do these variables represent? And how does grain stress severity influence grain number and subsequently yield formation?

I have attached a simulation run using a high emission scenario and the year 2070 for a site in Cameroon. Yields are 0, but I don't see any water stress using the variables of my output file. Maybe I'm looking at the wrong variables, but I have the feeling that my yield failure is due to the regular 40+ °C days during the flowering phase. The documentation says there is no temperature stress in the maize model though, which now has me a bit confused..

[Sim.zip](https://github.com/APSIMInitiative/APSIMClassic/files/10202273/Sim.zip)

**Comment by peter-devoil** [comment]
We tried hard to do documentation in classic, but as you see - what's there is often out of date and incorrect. Even in nextgen we struggle.  [This descriptive link](https://www.apsim.info/apsim-model/description-of-crop-growth-and-development-framework-in-apsim-crop-models/) has some general background, but little on heat stress.

Yes, there is a maxt effect on grain number, and it follows the general procedure outlined above. As you  might guess, there's a sensitivity window around flowering, and the amount of stress is described in that XY table: no stress at 32oC, 0.65 at 38oC. It's a daily calculation (made on every day in the window), and I *think* it's a time-weighted average of all hot days in the window - perhaps @jbrider may confirm this.

Don't overlook that reducing grain number in this manner is a sink limitation - if there are fewer fertile grains the potential yield is reduced, the _actual_ yield will be reduced even further (by water/N limitations).

You can report "GrainTempFactor" at harvest. Rather than relying on a long term weatherfile, I've found the "climate control"  in the manager toolbox a good way to push the model into obscene conditions that demonstrate these algorithms in action.

**Comment by LenLon** [comment]
Thanks a lot. For me, heat tolerance is a much more interesting adaptation option over early maturity (drought escape), as I have found no water stress for most of my sites (Sahel experiences a wetting trend under emission scenario ssp370). 

Is there a source for the numbers chosen as stress? And how do I interpret "0.65 stress at 38oC"? I did some limited calibration runs changing that number to "0.65 stress at 40oC" and I am seeing really good results for climate change impact reduction on yield, but I don't know how realistic changing that number is. After all, it's given in the species characteristics of the maize model, not for the cultivars, and I'd like my improved-variety adaptation strategy to somewhat resemble breeding capabilities for maize.

**Comment by peter-devoil** [comment]
Interpreting: 0 is no stress, 1 is full. The potential grain number is calculated from plant growth rate, then reduced by that fractional amount. Each stress value from single days is averaged over the window of sensitivity (I think).

@uqghamme or @jbrider might have tips on the derivation of that sensitivity table

**Comment by peter-devoil** [comment]
[Here's some work](https://doi.org/10.1093/insilicoplants/diz003) very similar to what's in apsim now .

**Comment by LenLon** [comment]
Thanks a lot for the info, that clarifies some things. Great that I can work on heat tolerance in APSIM now :)

@peter-devoil: I don't think the stress value is averaged, to me it looks like it is some sort of cumulative thing - it always starts at 1, then goes down to a certain value (e.g. 0.353) and stays there once grain filling starts. In hundreds of simulation years I have never seen it go up again, so it seems stress can't be reversed (or damage to the flowers/tassels is permanent).

**Comment by jbrider** [comment]
It's an accumulated weighted average using thermal time as the weighting multiplied by the stress value derived via the response table. That is correct, the stress cannot be reversed.
